---

- name: "configuration play" 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable"
      wait_for_connection:

    - name: "install python for Ansible"
      become: yes
      apt:
        name: ["python3"]
        state: latest
        update_cache: yes
   
    - name: "configure enviroment varibales"
      become: yes
      blockinfile:
        path: ~/.profile
        block: |
          export ENVIRONMENT=production
          export TYPEORM_CONNECTION=postgres
          export TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
          export TYPEORM_HOST=udapeople.cysdbdotwiie.us-west-2.rds.amazonaws.com
          export TYPEORM_PORT=5432
          export TYPEORM_USERNAME=postgres
          export TYPEORM_PASSWORD=udapeople123
          export TYPEORM_DATABASE=postgres

  roles:
    - configure-server