---

- name: "copy backend dist files to server"
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "install node modules"
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: "build package"
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: "run migrations again"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations

- name: "executing node"
  become: yes
  shell: |
    cd /home/ubuntu/backend 
    pm2 start npm --name backend -- start